### ISSUE TITLE
Not working on Azure

### ISSUE THREAD

**Issue by Milan4e** [l-ra/openeet-net#1]
Hi, 

Thanks for the library!

Have you tried this on Azure? I cannot make it work, I tried pretty much everything and I am getting kod=4 as error response from the EET service. Works fine locally.

Thanks!

**Comment by l-ra** [comment]
Can you describe more details how you use it? Is it plaxground or production? Are you running exe on azure virtual machine ? Are you deploying webrole worker ? 

Error no. 4 usually means wrong certificate is used. Do you use the latest build ?

**Comment by Milan4e** [comment]
Thanks for your message.

I am using Playground for now, I haven't tried with production, but I probably will first thing tomorrow.
The code is deployed as part of an azure website, I have a library where the EET service lives (very similar to your architecture) and the website is referencing and calling that library.

I create logs all over the library and i found out that:
Correct certificate is loaded
Correct password is used
Correct EET service URL is called

I triple checked environment variables in case thats the issue, but did not find anything.
Also, I have the latest build. I am happy to provide you with more details if necessary.
Thanks!

**Comment by l-ra** [comment]
the latest [build](https://github.com/l-ra/openeet/blob/master/releases/prerelease/openeet-lite-shapshot-20170303-1130.zip) is able to dump the most important data during signature computation. Can you turn the dumping on and send me the resulting files for analysis? To turn on dumping use `builder..dumpDataPath("path-to-store-dump-files");` several files will be created in `"path-to-store-dump-files"` when signing the request.

**Comment by DefinitionHigh** [comment]
Hello @l-ra ,

seems like this is the one solution that will work! Thakns for sharing.

BUT I have same issue, getting the error code 4 "Neplatny podpis SOAP zpravy".

I have dumped data... Can you help me make it work please?

[downloaded last build, built the library, referenced the library in my asp.net project]
[ERG.zip](https://github.com/l-ra/openeet-net/files/3811587/ERG.zip)

**Comment by l-ra** [comment]
When I try to validate the resulting message (`xmlTemplate-removedUnusedPlaceholders.bin`) locally it validates OK:
```
[XXXXX@localhost eet-2019-11-05]$ xmlsec1 --verify --pubkey-cert-pem cert.pem  xmlTemplate-removedUnusedPlaceholders.bin 
OK
SignedInfo References (ok/all): 1/1
Manifests References (ok/all): 0/0
```
Please confirm you are sending the message to the right endpoint. The message seems to be signed using production certificate. Do you send it to the production endpoint? When you send production message to playground the error is 4 "Neplatny podpis SOAP zpravy". 

For testing & development the testing certificates shall be used (https://www.etrzby.cz/assets/cs/prilohy/EET_CA1_Playground_v3.zip)

**Comment by DefinitionHigh** [comment]
in the morning, with coffee, the brain works better :)

thank you for your fast reply! now I see where is the problem. Althought I am setting the production "builder().overeni(Overeni.PRODUKCNI)" but I am sending the request "sendRequest(requestBody, "https://pg.eet.cz:443/eet/services/EETServiceSOAP/v3");". And I presume that "pg" subdomain means PlayGround. 

It will be better to have sendRequest method with requestBody parameter only ad this method should set service URL based on builder().overeni. What do you think?

**Comment by l-ra** [comment]
I do not actively maintain this code. I'll try my best only to keep it working if the ministry changes the EET interface. 
Feel free to clone the repo and customize it for your needs :-).

**Comment by l-ra** [comment]
And regarding the question about  `builder().overeni(Overeni.PRODUKCNI)` - it does not influence the signature validity. Playground (https://pg.eet.cz:443/eet/services/EETServiceSOAP/v3) expects non production certificates issued by non production CA. That is IMO why the message dump you sent has not a valid signature.

**Comment by DefinitionHigh** [comment]
Thank you for your support! Library now works for me (changed pg subdomain to prod).

I am giving STAR (would be 5stars if possible) for the ONLY working .NET solution for EET

Best regards!

**Comment by l-ra** [comment]
I'm glad it is helpful. I thing there are more .NET solutions but they usually contain lots of WCF/XMLDsig related complexities. I prefer simple solutions for simple problems :-).

And be aware! By changing subdomain to prod, you are already registering in production with full tax responsibility. Consider using PG and certificates published by the ministry for PG.
